# menggambar persamaan bidang dalam ruang 3D
$$\begin{split}
\begin{eqnarray*}
x_1 - x_2 + x_3 & = & 3\\
2x_1 + x_2 + 8x_3 & = & 18\\
4x_1 + 2x_2 -3x_3 & = & -2
\end{eqnarray*}
\end{split}$$

## penyelesaian sistem linier
penyelesaian sistem persamaan linier dg ,menggunakan elimininasi gaus

selesaikan persamaan berikut

$$
8x_1+x_2+x_3=19\\
x_1+2x_2+3x_3=9\\
2x_1+x_2+x_3=5
$$

berikut penyelesaian diatas

In [ ]:
import numpy as np

A = np.array([[8, 9, 1, 19],
              [1, 2, 3, 9,],
              [2, 1, 1, 5,]])

print(A)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]


##mendefinisikan fungsi operasi baris eliminasi gauss


*   RowSwap
*   RowScale
*   RowAdd





In [ ]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [ ]:
import numpy as np

A = np.array([[1, -1, 1],
              [2, 1, 8],
              [4, 2, -3]])

B = np.array([3, 18, -2])

X = np.linalg.solve(A, B)

print("Solusi:")
print("x1 =", X[0])
print("x2 =", X[1])
print("x3 =", X[2])


Solusi:
x1 = 1.0
x2 = -0.0
x3 = 2.0
